
pipeline {
    agent any
    triggers {
        pollSCM('* * * * *')
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
    }
    stages {
        stage('build') {
            steps {
                sh 'docker image build -t saikrishnna29/httpd:v1 Jenkins/jenkins-docker/Dockerfile'
            }
        }
        stage('Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('push') {
            steps {
                sh 'docker push saikrishnna/httpd:v1'
            }
        }
    }
}
